# This is a basic workflow to help you get started with Actions

name: Update

on:
  push:
    branches: [feature/small_fixes]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Cookie cache currently not working, because it's loosing the permission after some time
      #
      # - name: Cache cookies
      #   uses: actions/cache@v2
      #   with:
      #     path: ./cookies
      #     key: ${{ runner.os }}-${{ hashFiles('**/*.js') }}
      #     restore-keys: |
      #       ${{ runner.os }}-

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "17"

      - name: npm install
        run: |
          cd ./scripts
          npm install
          cd ..

      - name: update teams
        run: |
          node ./scripts/updateTeams.js "./teams" ${{ secrets.GH_TOKEN }}

      - name: update labels
        run: |
          node ./scripts/updateLabels.js "./teams" ${{ secrets.GH_TOKEN }}

      - name: update team boards
        id: update-team-boards
        run: |
          node ./scripts/updateTeamBoards.js "./teams" "./boards" ${{ secrets.GH_TOKEN }} ${{ secrets.ZENHUB_TOKEN }} ${{ secrets.GH_USERNAME }} ${{ secrets.GH_PASSWORD }} ${{ secrets.MAIL_USERNAME }} ${{ secrets.MAIL_PASSWORD }}
        # Continue on error to archive the last html page for further debugging
        continue-on-error: true
          
      
      # Archive files that have been written by the procedures in case of an error
      - name: Archive further logs from run for debugging
        if: steps.update-team-boards.outcome != 'success'
        uses: actions/upload-artifact@v3
        with:
          name: further-logs
          path: logs
            
      # Check if the before ignored error in updateTeamBoards step happened
      # then set the overall status to failed. Else failed runs are masked
      - name: Check on failures
        if: steps.update-team-boards.outcome != 'success'
        run: exit 1
